theme: minima
title: Códigos
author: LucasFig-log
email: lucassantosfig@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Veja alguns dos meus códigos

# social links
twitter_username: lucasfig16 # DO NOT include the @ character, or else the build will fail!
github_username:  LucasFig-log # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
